### ISSUE TITLE
About dufomap's Python API in process.py

### ISSUE THREAD

**Issue by RickyYXY** [KTH-RPL/SeFlow#5]
You have use dufomap in process.py, and now I want to use dufomap in my own project.
But I'm confused about the parameters for the dufomap function.
Like
`mydufo = dufomap(0.2, 0.2, 1, num_threads=12) # resolution, d_s, d_p, hit_extension`
`mydufo.setCluster(0, 20, 0.2) # depth=0, min_points=20, max_dist=0.2`
What does resolution, d_s, d_p, depth=0, min_points=20, max_dist=0.2 means?
Do you have a doc for dufomap function?
I have created a issue in dufomap's project, and I'm hope to get your respond, Thks!

**Comment by Kin-Zhang** [comment]
I think it's better to directly check DUFOMap paper and SeFlow supplementary paper to know the meaning.

And according to cluster function, feel free to comment it, since it's just for visualization and remove small set of cluster etc, and I tried first time in paper without it, I will comment it in case people get confused.
