### ISSUE TITLE
Result on the Argoverse 2 leaderboard

### ISSUE THREAD

**Issue by yanconglin** [KTH-RPL/SeFlow#6]
Hi,  thank you for releasing the codebase. 
I was wondering if you could kindly clarify the following questions? 
1. it seems the leaderboard result is much better than the reported values in the paper (e.g., EPE-3way). would you mind sharing some info on how you made this happen?
2. I have found several checkpoints. One is available at [deflow discussion on leaderboard result](https://github.com/KTH-RPL/DeFlow/discussions/2#discussioncomment-10088593) , denoted as "seflow_official", and another one is refered to as "seflow_best" available at [seflow_repo](https://github.com/KTH-RPL/DeFlow/discussions/2#discussioncomment-10088593).  Could you pleae let me know the differences between these two?
3. If I were about to make a comparison, let us say using the 1x setup without extra data, which one is to use? 

I look forward to your reply. Many thanks in advance.

**Comment by Kin-Zhang** [comment]
Hi, there is a note in the README: https://github.com/KTH-RPL/SeFlow?tab=readme-ov-file#other-benchmark-models

![image](https://github.com/user-attachments/assets/f8e93d13-41d0-4a49-a515-31cef05dfcf1)

* The paper result is under 2e-6 and epoch 50 to have fair ablation study with same setup on ZeroFlow since we directly use their weight.
* `seflow_official` is the weight I used in the paper result and leaderboard v1 result (since when I'm writing the paper, leaderboard v2 haven't published yet). And `seflow_best` is the weight I trained with the note said and the result in leaderboard version 2 (we also mentioned this in updated supplementary material.) config: 2e-4 and epoch 20. You can find that also using torch.load(model), all configs are saved in the model weight.
* Personally, I will say use the result on the leaderboard and the file name is `seflow_best.ckpt`.

**Comment by yanconglin** [comment]
Thank you for the clarification. Fair points.
One additional question: does the best result on benchmark follow a 1x or 2x setup?

**Comment by Kin-Zhang** [comment]
1x dataset size for all results in both leaderboards (v1, v2).
